```{r}

install.packages("remotes")
remotes::install_github("UrbanInstitute/urbnthemes", build_vignettes = TRUE)


library(tidyverse)
library(sf)
library(tmap)
library(here)
library(osmdata)
library(ggpattern)
library(tidycensus)
library(openxlsx)
library(urbnthemes)
library(skimr)

source(here("scripts", "get_acs_data.R"))
source(here("scripts", "plot_utility_functions.R"))
source(here("scripts", "plot_comparison_charts.R"))
source(here("scripts", "plot_boulevard_map.R"))
source(here("scripts", "plot_acs_maps.R"))
source(here("scripts", "get_non_acs_data.R"))


## Set working directory and file paths
## Adjust this to set file_path to direct to whichever folder you have the repo working out of
username <- getwd() %>% str_split("\\/") %>% unlist() %>% .[3]
file_path <- file.path(here())

options(
  tigris_use_cache = TRUE,
  scipen = 999999)
```

Set a boulevard variable

```{r}
boulevard = "hoover"
boulevard_tracts = file.path(file_path, boulevard, "maps", str_c(boulevard, "_buffer_tracts.shp")) %>%
  st_read(quiet = TRUE) %>% 
  st_set_crs(4326)
```

Obtaining ACS data

```{r}
acs_tracts_la = get_acs_data(
    file_path = file_path, 
    area = "LA",
    census_geography = "tract")

acs_tracts_boulevard = acs_tracts_la %>%
  filter(GEOID %in% boulevard_tracts$GEOID)

acs_city_la = get_acs_data(
  file_path = file_path, 
  area = "LA", 
  census_geography = "place") 
```

Plotting comparison charts

```{r, fig.width = 6.5, fig.height = 2.5}
color_palette = c(
  "LA City" = "#00447c",
  "Hoover St" = "#A7c539") ## adjust this label to whichever study area you are looking at

plot_metadata = tribble(
  ~constructs, ~denominators,
  "income", "B19001_001",
  "employment", "B23001_001",
  "age", "B01001_001",
  "ethnicity", "B03002_001",
  "family", "B11003_001",
  "english", "B16004_001",
  "language", "english_less_than_very_well_denominator",
  "device", "B28001_001",
  "commute_mode", "B08301_001",
  "commute_time", "B08303_001",
  "tenure", "B25003_001",
  "rent_burden", "rent_burden_denominator",
  "school", "B14007_001",
  "foreign_born", "B01001_001",
  "veteran", "B21001_001"
  )

comparison_charts = plot_comparison_charts(
  df_boulevard = acs_tracts_boulevard, 
  df_city = acs_city_la,
  boulevard_name = "Hoover St", ## adjust this label to whichever study area you are looking at
  color = color_palette,
  constructs = plot_metadata$constructs,
  denominators = plot_metadata$denominators,
  save = FALSE, ## Set this to TRUE to save plots to project folder
  outpath = file.path(file_path, boulevard, "Outputs"), ## adjust folder name of where you wants the plots saved to
  file_extension = ".png")

comparison_charts


```

Prepare spatial layers

```{r}
projection = 2229

## tracts
la_tracts <- st_read(file.path(file_path, "Data Analysis Instructions for SCA/Data/CA Census Tracts/CA_census_Tracts.shp")) %>% 
  filter(COUNTYFP == "037") #%>%
  #st_transform(projection) ## run this line if spatial projection is not working, should not be needed normally 


boulevard_tracts <- la_tracts %>%
  filter(GEOID %in% boulevard_tracts$GEOID)

## Comment/Uncomment the appropriate chunks for street/locations for each SCA area, streets/locations coordinates are found manually on google maps 
streets_sf = tribble(
  ~name, ~lat, ~lon, ~orientation, ~boulevard,
  
  #### Pico Streets ####
  # "Wilshire Blvd", 34.06217056027787, -118.29424612980146, 0, boulevard,
  # "Olympic Blvd", 34.05754326508076, -118.34502694326508, 0, boulevard,
  # "Washington Blvd", 34.040903520026625, -118.34737421737195, -10, boulevard,
  # "Rosa Parks Fwy", 34.036465982980886, -118.29767182226023, 0, boulevard,
  # "Adams Blvd", 34.03283003396823, -118.3254615038501, 0, boulevard,
  # "Jefferson Blvd", 34.02516133685176, -118.314070166191, 0, boulevard,
  # "La Brea Ave", 34.037457517681425, -118.34948870419119, 75, boulevard,
  # "Crenshaw Blvd", 34.059019617009476, -118.32025318579531, 67, boulevard,
  # "Arlington Ave", 34.03130279886178, -118.31775449166764, 90, boulevard,
  # "Western Ave", 34.03064831048125, -118.30907566457537, 90, boulevard,
  # "Normandie Ave", 34.03040186970061, -118.30027509279961, 90, boulevard,
  # "Vermont Ave", 34.031803023478986, -118.29147407689182, 90, boulevard,
  # "Hoover St", 34.03191105597345, -118.28495893090334, 90, boulevard,
  # "Harbor Fwy", 34.05418379708543, -118.25980368140354, 55, boulevard
  
  ### Hoover Streets ####
  "MLK Jr Blvd", 34.01114719258918, -118.26536648634915, 0, boulevard,
  "Vernon Ave", 34.003854692348405, -118.26536648634915, 0, boulevard,
  "Slauson Ave", 33.98932307117704, -118.26523319659992, 0, boulevard,
  "Florence Ave", 33.974733696872036, -118.25616655173909, 0, boulevard,
  "Manchester Ave", 33.960118221849065, -118.25607145690896, 0, boulevard,
  "Harbor Fwy", 33.982781626478186, -118.28060176708684, 270, boulevard,
  "Vermont Ave", 33.98235972870656, -118.29168835018301, 90, boulevard,
  "Normandie Ave", 33.98235972870656, -118.30030677623152, 90, boulevard,
  "Van Ness Ave", 33.983371941772745, -118.317750099191, 90, boulevard,
  "Crenshaw Blvd", 33.98297019442496, -118.33092846920148, 90, boulevard,
  "Main St", 33.982436755767004, -118.27400241679408, 270, boulevard,
  "Avalon Blvd", 33.98253230870111, -118.26521583140891, 270, boulevard,
  "Exposition Blvd", 34.018306424628975, -118.30579458465892, 0, boulevard,
  
  #### MLK East Streets ####
  # "Vernon Ave", 34.003854692348405, -118.26536648634915, 0, boulevard,
  # "Harbor Fwy", 33.997457650265595, -118.28060176708684, 90, boulevard,
  # "Vermont Ave", 33.997457650265595, -118.29157543208511, 90, boulevard,
  # "Main St", 33.997457650265595, -118.27400241679408, 90, boulevard,
  # "Avalon Blvd", 33.997457650265595, -118.26521583140891, 90, boulevard,
  # "S Central Ave", 33.997457650265595, -118.25654362606636, 90, boulevard,
  # "Compton Ave", 33.997457650265595, -118.24782315230883, 90, boulevard,
  # "Alameda St", 33.997457650265595, -118.23893194279209, 90, boulevard,
  # "Exposition Blvd", 34.018306424628975, -118.29579458465892, 0, boulevard,
  # "W Jefferson Blvd", 34.015349134822415, -118.26539713983982, 330, boulevard,
  # "W Adams Blvd", 34.02171394087482, -118.26149019886697, 330, boulevard,
  # "I-10 Highway", 34.02963863308693, -118.2562396832706, 330, 
  
  #### SaMo Streets ####
 #  "Wilshire Blvd", 34.04700814212168, -118.46389314403606, 46, boulevard,
 #  "I-405 Highway", 34.062111891101544, -118.45732644292302, 306, boulevard,
 #  "I-10 Highway", 34.02836949394677, -118.44887737870634, 10, boulevard,
 #  "San Vicente Blvd", 34.05190061515859, -118.47460501575662, 16, boulevard,
 # # "Santa Monica Blvd", 34.04581102898062, -118.45063133872866, 15, boulevard,
 #  #"Colorado Ave", 34.03062380737115, -118.47117687859794, 46, boulevard,
 #  #"Arizona Ave", 34.03464128056424, -118.47590358425937, 47, boulevard,
 #  "Ohio Ave", 34.04930514322892, -118.4485050408507, 41, boulevard,
 #  # "Texas Ave", 34.04151992820824, -118.46768450691522, 46, boulevard,
 #  # "Rochester Ave", 34.043276609278145, -118.4629094648567, 38, boulevard,
 #  # "S Saltair Ave", 34.040053333366586, -118.46143586068403, 305, boulevard,
 #  # "S Westgate Ave", 34.04132135746055, -118.45833072047674, 305, boulevard,
 #  "Westwood Blvd", 34.05404853759078, -118.44074349431331, 306, boulevard,
 #  "Centinela Ave", 34.03795663940399, -118.46699574515026, 315, boulevard,
 #  "Bundy Dr", 34.03239046333756, -118.4537232564416, 317, boulevard,
#  "City of Santa Monica\n(outside of LA City Jurisdiction)", 34.02879459572271, -118.47699596358547, 0, boulevard

  
  
  ) %>%
  st_as_sf(
    coords = c("lon", "lat"),
    crs = 4326) %>%
  #st_transform(projection) %>%
  filter(boulevard == !!boulevard)

#key locations
locations_sf = tribble(
  ~name, ~lat, ~lon, ~boulevard,
  
  #### Pico Locations ####
  # "Harold A Henry Park", 34.05771, -118.326204, boulevard,
  # "MacArthur Park", 34.059539, -118.277825, boulevard,
  # #"Los Angeles Elementary School", 34.04767415795226, -118.30564277817867, boulevard,
  # #"Los Angeles High School", 34.05631575779619, -118.33290205238154,  boulevard,
  # "Normandie Recreation Center", 34.044543, -118.299765, boulevard
  
  #### Hoover Locations ####
  "Exposition Park", 34.01465919961802, -118.28749014509255, boulevard,
  "Harvard Park", 33.984241239976996, -118.30467543777576, boulevard,
  "Algin Sutton Recreation Center", 33.95628624786266, -118.28592530502922, boulevard,
  "Augustus Hawkins High School", 33.98689352636203, -118.28809332457882, boulevard,
  "Vermont Square Park", 34.00025327505379, -118.2972922149193, boulevard,
  "South Park Recreation Center", 33.997457650265595, -118.26774886549762, boulevard,

  #### MLK East Locations ####
  # "Exposition Park", 34.01465919961802, -118.28749014509255, boulevard,
  # #"South Park Recreation Center", 33.997457650265595, -118.26774886549762, boulevard,  
  # "Thomas Jefferson High School", 34.00997417280373, -118.25116074723486, boulevard,
  # "Gilbert Lindsay Recreation Center", 34.00740067778371, -118.26759083665975, boulevard,
  # #"Santee High School", 34.028448683424934, -118.2634537575853, boulevard,
  # "University of Southern California", 34.02250540388042, -118.28501499219414, boulevard
  
  #### SaMo Locations ####
  #"UCLA", 34.064964656862095, -118.44536560778212, boulevard,
  #"West LA VA Medical Center", 34.05247315379336, -118.45295447084322, boulevard,
  #"University High School", 34.04561998108219, -118.46096278532994, boulevard,
  #"Beverly Hills High School", 34.061242565789044, -118.41023652161807, boulevard,
  #"Stoner Park", 34.03820077425739, -118.4539619445094, boulevard,
  #"The Getty", 34.07715346855072, -118.47442918126463, boulevard,
  #"Santa Monica Airport", 34.016609712728666, -118.45033595223472, boulevard
  
  ) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326) #%>%
  #st_transform(projection)

boulevard_outline <- st_union(boulevard_tracts) #%>%
  #st_transform(projection)


boulevard_corridor <- st_read(file.path(file_path, boulevard, "maps", paste0(boulevard, "_blvd.shp"))) %>%
  st_transform(4326) 
```


study area map
```{r}

## used to load in Santa Monica city boundaries, unused for other areas
# samo_limits <- st_read(file.path(file_path, boulevard, "maps", "City_Boundary.shp")) %>%
#   st_transform(4326) 

  bbox <- st_bbox(boulevard_corridor)
  xpad = 0.03 ## map boundary padding in the X or East/West direction; adjust as needed
  ypad = 0.014 ## map boundary padding in the Y or North/South direction; adjust as needed
    
  ## Add padding to x or y direction
  bbox["xmin"] <- bbox["xmin"] - xpad
  bbox["xmax"] <- bbox["xmax"] + xpad
  bbox["ymin"] <- bbox["ymin"] - ypad
  bbox["ymax"] <- bbox["ymax"] + ypad
  
  
map2 = 
    ## study area outline
    tm_shape(boulevard_corridor %>% st_buffer(825), bbox = bbox, is.main = TRUE, unit = "mi") +
      tm_borders(col = "#9e400f", lwd = 2, lty = "dashed") +
    ## the boulevard
    tm_shape(boulevard_corridor, bbox = bbox) +
      tm_lines(col = "#F4AB0B", lwd = 4) +
    tm_add_legend(
      type = "lines",
      col = c("#F4AB0B", "#9e400f"),
      lty = c("solid", "dashed"),
      lwd = c(2, 2),
      labels = c("Project Site", "Study Area"),
      frame.lwd = 0,
      position = tm_pos_on_top("left", "top"),
      bg.color = "white",    
      bg.alpha = 0.9,
      title.size = .8,        
      title.color = "black",  
      text.color = "black",   
      title.fontface = "bold"
    ) +
    # tm_shape(samo_limits) +
    #   tm_polygons(fill = "darkgrey", fill_alpha = .5, col = "black", lwd = .5) +  ## Used to add Santa Monica City limits, unused for other areas
    tm_shape(
      locations_sf %>% mutate(name = str_wrap(name, 20)), bbox = bbox) +
      tm_dots(
        col = "black",
        size = 0.4) +
      tm_text(
        "name",
        size = 0.6,
        col = "black",
        options = opt_tm_text(just = "center"),
        ymod = 1.5,
        fontface = "bold",
        fontfamily = "Calibri") +
    tm_shape(
      streets_sf, bbox = bbox) +
      tm_text(
        "name",
        size = 0.6,
        col = "black",
        angle = "orientation",
        options = opt_tm_text(just = "center"),
        fontface = "bold",
        fontfamily = "Calibri") +
    ## a compass
    tm_compass(
      type = "arrow", 
      size = 1,
      #group_id = "bottom_right",
      position = c(.70, .08), ## position in the bottom right of the map, adjust as needed
      stack = "horizontal"
      ) +
    ## a scalebar
    tm_scalebar(
      breaks = c(0, .5, 1),
      #group_id = "bottom_right",
      position = c(.72, .07), ## position in the bottom right of the map, adjust as needed
      text.size = .7,
      stack = "horizontal"
      ) +
    ## the legend
    tm_layout(
      legend.position = tm_pos_on_top("left", "bottom"),
      frame = FALSE,
      legend.frame = FALSE,
      #legend.width = 8,
      legend.bg.color = "white",    
      legend.bg.alpha = 0.9,
      legend.title.size = .8,        
      legend.title.color = "black",  
      legend.text.color = "black",   
      legend.title.fontface = "bold") +
    ## the basemap
    tm_basemap("Esri.WorldGrayCanvas")

map2

tmap_save(map2, file = here(file_path, boulevard, "Outputs", "study_area_map.png"), height = 5, width = 6, dpi = 2000)


```




Plot chloropleths

```{r, fig.width = 6.5, fig.height = 4.5}

## create plot metadata as a tribble with `fill_column` and `legend_title
plot_metadata = tribble(
  ~fill_column, ~legend_title,
  "population_density_sqmi", "Population Density\n(sq. mi)",
  "share_disability", "With a Disability",
  "B19013_001", "Median Income",
  "share_below_poverty", "Below Poverty Level",
  "share_no_internet", "No Internet Access",
  "share_no_computer", "No Computer Access",
  "share_renter_occupied", "Renter-Occupied",
  "share_no_car", "No Vehicle Access",
  "share_commute_hour_plus", "Commute Time (1 hour+)",
  "share_speak_korean_at_home", "Speak Korean at Home",
  "share_speak_spanish_at_home", "Speak Spanish at Home",
  "share_renter_housing_costburden_30plus", "Housing Cost Burden (30%+)",
  "share_renter_housing_costburden_50plus", "Housing Cost Burden (50%+)",
  "B25071_001", "Housing as Share of Income, Median"
)

plot_acs_maps(
  sf = acs_tracts_boulevard,
  boulevard_sf = boulevard_corridor,
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  fill_column = plot_metadata$fill_column,
  legend_title = plot_metadata$legend_title,
  xpad = 4500,
  ypad = 3750,
  bins = 4,
  scale_bar_position = .74,
  compass_position = .72, 
  height = 4.5,
  width = 6,
  save = FALSE,
  outpath = file.path(file_path, boulevard, "Outputs"),
  file_extension = ".png")
```

Non-ACS data

```{r}
affordable_housing_sf = get_non_acs_data(
  base_path = file_path,
  dataset_name = "affordable_housing",
  area = boulevard) %>%
  st_transform(projection) %>% 
  mutate(dataset = "Affordable Housing Development")

senior_housing_sf = get_non_acs_data(
  base_path = file_path,
  dataset_name = "senior_housing",
  area = boulevard) %>% 
  mutate(dataset = "Senior Housing Development")

zoning_sf = get_non_acs_data(
  base_path = file_path,
  dataset_name = "zoning",
  area = boulevard) %>%
  st_intersection(boulevard_corridor %>% st_buffer(2640))

h_and_t_sf = boulevard_tracts %>%
  select(GEOID) %>%
  left_join(
    get_non_acs_data(
      base_path = file_path,
      dataset_name = "h_and_t",
      area = boulevard)) 

crash_sf = get_non_acs_data(
  base_path = file_path,
  dataset_name = "crash",
  area = boulevard) %>% 
  mutate(crash_type = factor(crash_type, levels = c("Pedestrian involved severe crash",
                                                    "Bicyclist involved severe crash"))) %>% 
  filter(crash_type != "Other vehicle severe crash")

crash_full_sf = get_non_acs_data(
  base_path = file_path,
  dataset_name = "crash_full",
  area = boulevard) %>%
    mutate(crash_type = factor(crash_type, levels = c("Pedestrian involved severe crash",
                                                    "Bicyclist involved severe crash",
                                                    "Other vehicle severe crash")))
  #filter(crash_type != "Other vehicle severe crash")

hla_sf = get_non_acs_data(
  base_path = file_path,
  dataset_name = "hla",
  area = boulevard) 

```

Non-ACS maps

```{r, fig.width = 6.5, fig.height = 4.5}

## affordable housing
plot_boulevard_map(
  tracts_sf = boulevard_tracts,
  sf = affordable_housing_sf,
  boulevard_sf = boulevard_corridor,
  fill_column = "dataset",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 4000,
  ypad = 1500,
  scale_bar_position = 0.66,
  compass_position = 0.63,
  height = 6.5,
  width = 4.5,
  projection = projection,
  legend_title = "",
  #style = "cont",
  map_type = "point",
  palette_colors = c("Affordable Housing Development" = "#00447C"),
  save = FALSE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))

## senior housing
plot_boulevard_map(
  tracts_sf = boulevard_tracts,
  sf = senior_housing_sf,
  boulevard_sf = boulevard_corridor,
  fill_column = "dataset",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 4000,
  ypad = 1500,
  scale_bar_position = 0.66,
  compass_position = 0.63,
  height = 6.5,
  width = 4.5,
  projection = projection,
  legend_title = "",
  palette_colors = c("Senior Housing Development" = "#00447C"),
  style = "cont",
  map_type = "point",
  save = TRUE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))

## zoning
plot_boulevard_map(
  tracts_sf = boulevard_tracts,
  sf = zoning_sf,
  boulevard_sf = boulevard_corridor,
  fill_column = "zoning_category",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 5000,
  ypad = 1500,
  scale_bar_position = 0.70,
  compass_position = 0.67,
  height = 6.5,
  width = 5,
  projection = projection,
  legend_title = "Zoning",
  palette_colors = c(
    "Agricultural or Open Space" = "#00447C",
    "Highways or Parking" = "#A7C539",
    "Commercial or Industrial" = "#F2B705",
    "Multi-family Residential" = "#780032",
    "Single-family Residential" = "#e66a8c",
    "Public" = "#D9D9D9"),
  style = "cat",
  map_type = "choropleth",
  border_color = NA,
  save = TRUE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))

## crashes
plot_boulevard_map(
  tracts_sf = boulevard_tracts,
  sf = crash_sf,
  boulevard_sf = boulevard_corridor,
  fill_column = "crash_type",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 3000,
  ypad = 1500,
  scale_bar_position = 0.62,
  compass_position = 0.59,
  height = 6.5,
  width = 4.5,
  projection = projection,
  legend_title = "Crashes",
  palette_colors = c("Pedestrian involved severe crash" = "#00447C",
                     "Bicyclist involved severe crash" = "#A7C539"),
  map_type = "point",
  border_color = NA,
  save = FALSE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))

plot_boulevard_map(
  tracts_sf = boulevard_tracts,
  sf = crash_full_sf,
  boulevard_sf = boulevard_corridor,
  fill_column = "crash_type",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 2000,
  ypad = 1500,
  scale_bar_position = 0.64,
  compass_position = 0.61,
  height = 4.5,
  width = 6.5,
  projection = projection,
  legend_title = "All Crashes",
  palette_colors = c("Pedestrian involved severe crash" = "#00447C",
                     "Bicyclist involved severe crash" = "#A7C539", 
                     "Other vehicle severe crash" = "#780032"),
  map_type = "point",
  border_color = NA,
  save = FALSE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))


## hla (mobility improvements vote measure)
plot_boulevard_map(
  sf = hla_sf,
  boulevard_sf = boulevard_corridor,
  fill_column = "hla_affirmative_vote_share",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 5000,
  ypad = 2500,
  scale_bar_position = 0.71,
  compass_position = 0.69,
  height = 4.5,
  width = 6.5,
  projection = projection,
  legend_title = "HLA Supporting",
  bins = 2,
  map_type = "choropleth",
  border_color = "white",
  style = "cont",
  save = TRUE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))

 

## housing and transportation affordability index (h+t)
## (but actually we're just plotting transportation costs)
plot_boulevard_map(
  sf = h_and_t_sf %>% mutate(t_ami = t_ami / 100),
  boulevard_sf = boulevard_corridor,
  fill_column = "t_ami",
  locations_sf = locations_sf,
  study_area_outline_sf = boulevard_outline,
  streets_sf = streets_sf,
  xpad = 3000,
  ypad = 1500,
  height = 4.5,
  width = 6.5,
  projection = projection,
  legend_title = "Transportation as Share of Income",
  map_type = "choropleth",
  border_color = "white",
  style = "cont",
  save = TRUE,
  file_extension = ".png",
  outpath = file.path(file_path, boulevard, "Outputs"))



```

Table 1: Top Countries for Foreign-born Study Area Residents

```{r}
acs_tracts_boulevard %>%
  st_drop_geometry %>%
  ## table on foreign-born persons by country
  select(GEOID, matches("B05006_")) %>%
  pivot_longer(-GEOID, names_to = "variable", values_to = "estimate") %>% 
  
  ## turning census variables from table B05006 into their respectives country names, must manually add countries for different areas if you think a group is missing out
  mutate(
    country = case_when(
      variable == "B05006_001" ~ "Table universe",
      variable == "B05006_158" ~ "Guatemala",
      variable == "B05006_157" ~ "El Salvador",
      variable == "B05006_160" ~ "Mexico",
      variable == "B05006_054" ~ "Korea",
      variable == "B05006_049" ~ "China",
      variable == "B05006_074" ~ "Phillipines",
      variable == "B05006_159" ~ "Honduras",
      variable == "B05006_080" ~ "Armenia",
      variable == "B05006_061" ~ "Iran",
      variable == "B05006_050" ~ "China",
      TRUE ~ NA_character_)) %>%
  summarize(
    .by = country, 
    estimate = sum(estimate, na.rm = TRUE)) %>%
  filter(!is.na(country), estimate > 1000) %>% ## Only keeping countries with more than 1000 residents, can adjust if needed
  arrange(desc(estimate)) #%>%
  mutate(share = round((estimate / estimate[country == "Table universe"]) * 100, digits = 0))
```

```{r Other charts}

any_disability_count <- acs_tracts_boulevard |>
  st_drop_geometry() |>
  select(B18101_004, B18101_007, B18101_010, B18101_013, B18101_016, B18101_019, B18101_023, B18101_026, B18101_029, B18101_032, B18101_035, B18101_038) |>
  mutate(disability = rowSums(across(starts_with("B18101")))) |>
   select(disability) |>
  summarise(across(everything(), sum, na.rm = TRUE))

disability_counts <- acs_tracts_boulevard |>
  st_drop_geometry() |>
  select(B18101_004, B18101_007, B18101_010, B18101_013, B18101_016, B18101_019, B18101_023, B18101_026, B18101_029, B18101_032, B18101_035, B18101_038,
         B18102_004, B18102_007, B18102_010, B18102_013, B18102_016, B18102_019, B18102_023, B18102_026, B18102_029, B18102_032, B18102_035, B18102_038,
         B18103_004, B18103_007, B18103_010, B18103_013, B18103_016, B18103_019, B18103_023, B18103_026, B18103_029, B18103_032, B18103_035, B18103_038,
         B18104_004, B18104_007, B18104_010, B18104_013, B18104_016, B18104_020, B18104_023, B18104_026, B18104_029, B18104_032,
         B18105_004, B18105_007, B18105_010, B18105_013, B18105_016, B18105_020, B18105_023, B18105_026, B18105_029, B18105_032,
         B18106_004, B18106_007, B18106_010, B18106_013, B18106_016, B18106_020, B18106_023, B18106_026, B18106_029, B18106_032,
         B18107_004, B18107_007, B18107_010, B18107_013, B18107_017, B18107_020, B18107_023, B18107_026,
         ) |>
  mutate(disability = rowSums(across(starts_with("B18101"))),
         hearing_difficulty = rowSums(across(starts_with("B18102"))),
         vision_difficulty = rowSums(across(starts_with("B18103"))),
         cognitive_difficulty = rowSums(across(starts_with("B18104"))),
         ambulatory_difficulty = rowSums(across(starts_with("B18105"))),
         self_care_difficulty = rowSums(across(starts_with("B18106"))),
         independent_living_difficulty = rowSums(across(starts_with("B18107"))),
         ) |>
  select(ends_with(c("_difficulty"))) |>
  summarise(across(everything(), sum, na.rm = TRUE)) |>
  gather(key = "Disability", value = "Count") |>
  mutate(percent = (Count/ any_disability_count[[1]]) * 100, 
         label = paste0(scales::comma(Count), " (", round(percent, 1), "%)"))





 disability_plot <- ggplot(disability_counts, aes(x = Disability, y = Count, fill = Disability)) +
  geom_col() +
  geom_text(
      aes(label = label),
      position = position_dodge(width = 0.8),
      vjust = -.5,
      color = "black",
      size = 8,
      size.unit = "pt") +
    scale_fill_manual(values = c("#00447C", "#A7C539", "#F2B705", "#780032", "#e66a8c","#D9D9D9", "black")) +
    scale_x_discrete(labels = c(
                                "disability" = "Any Disabilty ",
                                "ambulatory_difficulty" = "Ambulatory", 
                                "cognitive_difficulty" = "Cognitive", 
                                "hearing_difficulty" = "Hearing", 
                                "independent_living_difficulty" = "Independent Living", 
                                "self_care_difficulty" = "Self Care", 
                                "vision_difficulty" = "Vision" 
                                )) +
    scale_y_continuous(label = scales::comma) +
    theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      legend.position = "none",
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"))
 

disability_plot

ggsave(filename = "disability_counts.png", 
       plot = disability_plot, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 3.2,
       width = 6.84,
       dpi = 1000)

## bar chart of all crashed in the area
crashes_all_bar <- ggplot(crash_full_sf) +
  geom_bar(aes(x = crash_type, fill = crash_type)) + 
  scale_fill_manual(values = c("Pedestrian involved severe crash" = "#00447C",
                               "Bicyclist involved severe crash" = "#A7C539", 
                     "Other vehicle severe crash" = "#780032")) +
  geom_text(stat='count', 
      aes(x = crash_type, label=..count..),
      position = position_dodge(width = 0.8),
      vjust = -.5,
      color = "black",
      size = 8,
      size.unit = "pt") +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      legend.position = "none",
      text = element_text(family = "Arial", color = "black"))
 
crashes_all_bar

ggsave(filename = "all_crashes_bar.png", 
       plot = crashes_all_bar, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 3.6,
       width = 6.84,
       dpi = 1000)

## bar chart of crashes along site
crashes_bar <- ggplot(crash_sf) +
  geom_bar(aes(x = crash_type, fill = crash_type)) + 
  scale_fill_manual(values = c("Pedestrian involved severe crash" = "#00447C",
                               "Bicyclist involved severe crash" = "#A7C539", 
                     "Other vehicle severe crash" = "#780032")) +
    geom_text(stat='count', 
      aes(x = crash_type, label=..count..),
      position = position_dodge(width = 0.8),
      vjust = -.5,
      color = "black",
      size = 8,
      size.unit = "pt") +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      legend.position = "none",
      text = element_text(family = "Arial", color = "black"))
 
crashes_bar

ggsave(filename = "crashes_bar.png", 
       plot = crashes_bar, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 3.6,
       width = 6.84,
       dpi = 1000)


## bar chart of HLA voting

hla_all_city <- st_read(file.path(file_path, "Data/Measure HLA Vote/HLA.shp")) %>% 
      st_make_valid() %>%
      st_transform(crs = 4326) %>%
      st_drop_geometry() %>% 
      transmute(
        hla_total_vote_count = V3_LOS_A_4,
        hla_affirmative_vote_count = V3_LOS_A_2,
        hla_affirmative_vote_share = V3_LOS_A_5) %>% 
  summarise(across(everything(), sum, na.rm = T)) %>% 
  mutate(hla_affirmative_vote_share = hla_affirmative_vote_count/hla_total_vote_count,
         area = "LA City")

hla_boulevard <- hla_sf %>% 
  st_drop_geometry() %>%
  summarise(across(starts_with("hla"), sum, na.rm = T)) %>% 
  mutate(hla_affirmative_vote_share = hla_affirmative_vote_count/hla_total_vote_count,
         area = "Hoover St") ## adjust boulevard name as needed

hla_combined <- bind_rows(hla_boulevard, hla_all_city) %>%
  select(area, hla_affirmative_vote_share) %>% 
  pivot_longer(cols = c(hla_affirmative_vote_share)) %>% 
  mutate(variable = "Share of affirmative votes",
         area = factor(area, levels = c("Hoover St", "LA City"))) ## adjust boulevard name as needed


hla_supplement <- read_csv(file.path(file_path, "raw_data/Measure HLA Vote/hla_participation_data.csv")) %>% 
  filter(TYPE == "TOTAL") %>% 
  summarise(across(c(REGISTRATION, `BALLOTS CAST`, YES, NO), sum, na.rm = T)) %>%
  mutate(total_eligible_pop = sum(acs_city_la$B29001_001),
         percent_registered = REGISTRATION/total_eligible_pop,
         percent_reg_voted = `BALLOTS CAST`/ REGISTRATION,
         yes_share = YES/`BALLOTS CAST`,
         area = "LA City"
           )

hla_supplement_boulevard <- read_csv(file.path(file_path, "raw_data/Measure HLA Vote/hla_participation_data.csv")) %>% 
  filter(TYPE == "TOTAL" & PRECINCT %in% hla_sf$Precinct) %>%
  summarise(across(c(REGISTRATION, `BALLOTS CAST`, YES, NO), sum, na.rm = T)) %>%
  mutate(total_eligible_pop = sum(acs_tracts_boulevard$B29001_001),
         percent_registered = REGISTRATION/total_eligible_pop,
         percent_reg_voted = `BALLOTS CAST`/ REGISTRATION,
         yes_share = YES/`BALLOTS CAST`,
         area = "Hoover St" ## adjust boulevard name as needed
           )

hla_supplement_combined <-  bind_rows(hla_supplement, hla_supplement_boulevard) %>% 
  select(area, percent_registered, percent_reg_voted) %>% 
  pivot_longer(cols = c(percent_registered, percent_reg_voted)) %>% 
  mutate(variable = case_when(
    name == "percent_registered" ~ "Percent of eligbile residents registered to vote",
    name == "percent_reg_voted" ~ "Eligible voter participation" ),
    variable = factor(variable, levels = c("Percent of eligbile residents registered to vote", "Eligible voter participation" )),
    area = factor(area, levels = c("Hoover St", "LA City")) ) ## adjust boulevard name as needed


hla_participation_bar <- ggplot(hla_supplement_combined) +
  geom_col(aes(x = variable, y = value, fill = area), position = position_dodge(width = 0.8)) + 
  scale_fill_manual(values = c("LA City" = "#00447C", "Hoover St" = "#A7C539")) + ## adjust boulevard name as needed
  geom_text(aes(x = variable, y = value, label =scales::percent(value, accuracy = 1), group = area),
            position = position_dodge(width = 0.8),
            vjust = -.5,
            color = "black",
            size = 8,
            size.unit = "pt") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"))



hla_bar <- ggplot(hla_combined) +
  geom_col(aes(x = variable, y = value, fill = area), position = position_dodge(width = 0.8)) + 
  scale_fill_manual(values = c("LA City" = "#00447C", "Hoover St" = "#A7C539")) + ## adjust boulevard name as needed
  geom_text(aes(x = variable, y = value, label =scales::percent(value, accuracy = 1), group = area),
            position = position_dodge(width = 0.8),
            vjust = -.5,
            color = "black",
            size = 8,
            size.unit = "pt") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"))

hla_bar
hla_participation_bar

ggsave(filename = "hla_bar.png", 
       plot = hla_bar, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 3.6,
       width = 6.84,
       dpi = 1000)


hla_supplement <- read_csv(file.path(file_path, "raw_data/Measure HLA Vote/hla_participation_data.csv")) %>% 
  filter(TYPE == "TOTAL") %>% 
  summarise(across(c(REGISTRATION, `BALLOTS CAST`, YES, NO), sum, na.rm = T)) %>%
  mutate(total_eligible_pop = sum(acs_city_la$B29001_001),
         percent_registered = REGISTRATION/total_eligible_pop,
         percent_reg_voted = `BALLOTS CAST`/ REGISTRATION,
         yes_share = YES/`BALLOTS CAST`,
         area = "LA City"
           )

hla_supplement_boulevard <- read_csv(file.path(file_path, "raw_data/Measure HLA Vote/hla_participation_data.csv")) %>% 
  filter(TYPE == "TOTAL" & PRECINCT %in% hla_sf$Precinct) %>%
  summarise(across(c(REGISTRATION, `BALLOTS CAST`, YES, NO), sum, na.rm = T)) %>%
  mutate(total_eligible_pop = sum(acs_tracts_boulevard$B29001_001),
         percent_registered = REGISTRATION/total_eligible_pop,
         percent_reg_voted = `BALLOTS CAST`/ REGISTRATION,
         yes_share = YES/`BALLOTS CAST`,
         area = "Hoover St" ## adjust boulevard name as needed
           )

hla_supplement_combined <-  bind_rows(hla_supplement, hla_supplement_boulevard) %>% 
  select(area, percent_registered, percent_reg_voted) %>% 
  pivot_longer(cols = c(percent_registered, percent_reg_voted)) %>% 
  mutate(variable = case_when(
    name == "percent_registered" ~ "Percent of eligbile residents registered to vote",
    name == "percent_reg_voted" ~ "Eligible voter participation" ),
    variable = factor(variable, levels = c("Percent of eligbile residents registered to vote", "Eligible voter participation" )),
    area = factor(area, levels = c("Hoover St", "LA City")) ) ## adjust boulevard name as needed


hla_participation_bar <- ggplot(hla_supplement_combined) +
  geom_col(aes(x = variable, y = value, fill = area), position = position_dodge(width = 0.8)) + 
  scale_fill_manual(values = c("LA City" = "#00447C", "Hoover St" = "#A7C539")) + ## adjust boulevard name as needed
  geom_text(aes(x = variable, y = value, label =scales::percent(value, accuracy = 1), group = area),
            position = position_dodge(width = 0.8),
            vjust = -.5,
            color = "black",
            size = 8,
            size.unit = "pt") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"))

hla_participation_bar

ggsave(filename = "hla_participation_bar.png", 
       plot = hla_participation_bar, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 3.6,
       width = 6.84,
       dpi = 1000)




commute_mode_age_city <- acs_city_la |>
  st_drop_geometry() |>
  select(B08101_010, B08101_011, B08101_012, B08101_013, B08101_014, B08101_015, B08101_016,
         B08101_018, B08101_019, B08101_020, B08101_021, B08101_022, B08101_023, B08101_024,
         B08101_026, B08101_027, B08101_028, B08101_029, B08101_030, B08101_031, B08101_032,
         B08101_034, B08101_035, B08101_036, B08101_037, B08101_038, B08101_039, B08101_040,
         B08101_042, B08101_043, B08101_044, B08101_045, B08101_046, B08101_047, B08101_048,
         B08101_050, B08101_051, B08101_052, B08101_053, B08101_054, B08101_055, B08101_056
         ) |>
  pivot_longer(cols = everything()) |>
  mutate(age = case_when(
    name %in% c("B08101_010", "B08101_018", "B08101_026", "B08101_034", "B08101_042", "B08101_050",
                "B08101_011", "B08101_019", "B08101_027", "B08101_035", "B08101_043", "B08101_051") ~ "16-24",
    name %in% c("B08101_012", "B08101_020", "B08101_028", "B08101_036", "B08101_044", "B08101_052") ~ "25-44",
    name %in% c("B08101_013", "B08101_021", "B08101_029", "B08101_037", "B08101_045", "B08101_053",
                "B08101_014", "B08101_022", "B08101_030", "B08101_038", "B08101_046", "B08101_054") ~ "45-59",
    name %in% c("B08101_015", "B08101_023", "B08101_031", "B08101_039", "B08101_047", "B08101_055",
                "B08101_016", "B08101_024", "B08101_032", "B08101_040", "B08101_048", "B08101_056") ~ "60+"),
    mode = case_when(
      name %in% c("B08101_010", "B08101_011", "B08101_012", "B08101_013", "B08101_014", "B08101_015", "B08101_016") ~ "Car, truck, or van",
      name %in% c("B08101_018", "B08101_019", "B08101_020", "B08101_021", "B08101_022", "B08101_023", "B08101_024") ~ "Carpool",
      name %in% c("B08101_026", "B08101_027", "B08101_028", "B08101_029", "B08101_030", "B08101_031", "B08101_032") ~ "Public transportation",
      name %in% c("B08101_034", "B08101_035", "B08101_036", "B08101_037", "B08101_038", "B08101_039", "B08101_040") ~ "Walk",
      name %in% c("B08101_042", "B08101_043", "B08101_044", "B08101_045", "B08101_046", "B08101_047", "B08101_048") ~ "Taxicab, motorcycle, bicycle, or other",
      name %in% c("B08101_050", "B08101_051", "B08101_052", "B08101_053", "B08101_054", "B08101_055", "B08101_056") ~ "Worked from home"
    )
  ) |>
  group_by(age, mode) |>
  summarise(count = sum(value)) |>
  group_by(age) |>
  mutate(age_total = sum(count)) |>
  ungroup() |>
  mutate(percent = count/age_total,
         area = "LA City")


commute_age_mode_bar <- ggplot(commute_mode_age_city) +
  geom_col(aes(x = age, y = percent, fill = mode), position = position_dodge(width = 0.8)) + 
  scale_fill_manual(values = c("#00447C", "#A7C539", "#F2B705", "#780032", "#e66a8c","#D9D9D9")) +
  geom_text(aes(x = age, y = percent, label =scales::percent(percent, accuracy = 1), group = mode),
            position = position_dodge(width = 0.8),
            vjust = -.5,
            color = "black",
            size = 8,
            size.unit = "pt") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"))


  

commute_mode_age_boulevard <- acs_tracts_boulevard |>
  st_drop_geometry() |>
  select(B08101_010, B08101_011, B08101_012, B08101_013, B08101_014, B08101_015, B08101_016,
         B08101_018, B08101_019, B08101_020, B08101_021, B08101_022, B08101_023, B08101_024,
         B08101_026, B08101_027, B08101_028, B08101_029, B08101_030, B08101_031, B08101_032,
         B08101_034, B08101_035, B08101_036, B08101_037, B08101_038, B08101_039, B08101_040,
         B08101_042, B08101_043, B08101_044, B08101_045, B08101_046, B08101_047, B08101_048,
         B08101_050, B08101_051, B08101_052, B08101_053, B08101_054, B08101_055, B08101_056
         ) |>
  summarise(across(everything(), sum)) |>
  pivot_longer(cols = everything()) |>
  mutate(age = case_when(
    name %in% c("B08101_010", "B08101_018", "B08101_026", "B08101_034", "B08101_042", "B08101_050",
                "B08101_011", "B08101_019", "B08101_027", "B08101_035", "B08101_043", "B08101_051") ~ "16-24",
    name %in% c("B08101_012", "B08101_020", "B08101_028", "B08101_036", "B08101_044", "B08101_052") ~ "25-44",
    name %in% c("B08101_013", "B08101_021", "B08101_029", "B08101_037", "B08101_045", "B08101_053",
                "B08101_014", "B08101_022", "B08101_030", "B08101_038", "B08101_046", "B08101_054") ~ "45-59",
    name %in% c("B08101_015", "B08101_023", "B08101_031", "B08101_039", "B08101_047", "B08101_055",
                "B08101_016", "B08101_024", "B08101_032", "B08101_040", "B08101_048", "B08101_056") ~ "60+"),
    mode = case_when(
      name %in% c("B08101_010", "B08101_011", "B08101_012", "B08101_013", "B08101_014", "B08101_015", "B08101_016") ~ "Car, truck, or van",
      name %in% c("B08101_018", "B08101_019", "B08101_020", "B08101_021", "B08101_022", "B08101_023", "B08101_024") ~ "Carpool",
      name %in% c("B08101_026", "B08101_027", "B08101_028", "B08101_029", "B08101_030", "B08101_031", "B08101_032") ~ "Public transportation",
      name %in% c("B08101_034", "B08101_035", "B08101_036", "B08101_037", "B08101_038", "B08101_039", "B08101_040") ~ "Walk",
      name %in% c("B08101_042", "B08101_043", "B08101_044", "B08101_045", "B08101_046", "B08101_047", "B08101_048") ~ "Taxicab, motorcycle, bicycle, or other",
      name %in% c("B08101_050", "B08101_051", "B08101_052", "B08101_053", "B08101_054", "B08101_055", "B08101_056") ~ "Worked from home"
    )
  ) |>
  group_by(age, mode) |>
  summarise(count = sum(value)) |>
  group_by(age) |>
  mutate(age_total = sum(count)) |>
  ungroup() |>
  mutate(percent = count/age_total,
         area = "Hoover St")


commute_age_mode_area <- ggplot(commute_mode_age_boulevard) +
  geom_col(aes(x = age, y = percent, fill = mode), position = position_dodge(width = 0.8)) + 
  scale_fill_manual(values = c("#00447C", "#A7C539", "#F2B705", "#780032", "#e66a8c","#D9D9D9")) +
  geom_text(aes(x = age, y = percent, label =scales::percent(percent, accuracy = 1), group = mode),
            position = position_dodge(width = 0.8),
            vjust = -.5,
            color = "black",
            size = 8,
            size.unit = "pt") +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_urbn_print() +
    labs(x = "", y = "") +
    theme(
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"),
      legend.position = "none")


commute_age_mode_bar
commute_age_mode_area

ggsave(filename = "city_commute_age_mode_bar.png", 
       plot = commute_age_mode_bar, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 4.6,
       width = 6.84,
       dpi = 2000)

ggsave(filename = "area_commute_age_mode_bar.png", 
       plot = commute_age_mode_area, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 4.2,
       width = 6.84,
       dpi = 2000)




commute_age_combined <- commute_mode_age_boulevard %>% 
  bind_rows(commute_mode_age_city) %>% 
  mutate(area = factor(area, levels = c("Hoover St", "LA City")))

commute_age_mode_combined <- ggplot(commute_age_combined) +
  geom_col_pattern(aes(x = mode, y = percent, fill = mode, pattern = area), 
                   position = position_dodge2(width = .9, preserve = "single", padding = 0.1),
                   width = 1,
                   pattern_fill = "white",
                   pattern_color = "white",
                   pattern_angle = 90,
                   pattern_density = .3,
                   pattern_spacing = 0.01,
                   pattern_size = .01,
                   pattern_key_scale_factor = 0.6
                   ) + 
  geom_text(aes(x = mode, y = percent, label = scales::percent(percent, accuracy = 1), pattern = area), 
            vjust = -0.5, 
            position = position_dodge2(width = .9, preserve = "single", padding = 0.1)) +
  scale_pattern_manual(values = c("none", "crosshatch")) +
  facet_wrap(~age) +
  scale_fill_manual(values = c("#00447C", "#A7C539", "#F2B705", "#780032", "#e66a8c","black")) +

  scale_x_discrete(expand = expansion(mult = c(.1, .1))) +
  scale_y_continuous(labels = scales::percent_format()) +
  theme_urbn_print() +
   guides(
    fill = guide_legend(
      title = "Fill Color",
      override.aes = list(pattern = "none"),
      ncol = 2
    ),
    pattern = guide_legend(
      override.aes = list(size = 0.5),
      keyheight = unit(1, "lines")
    )
  ) +

    theme(
      panel.grid.major.x = element_blank(),
      text = element_text(family = "Arial", color = "black"),
    legend.position = "top",
    legend.direction = "vertical",
    legend.spacing.y = unit(8, "pt"),
    legend.margin = margin(t = 10, b = 10),
    #legend.key.size = unit(1, "lines"), 
    legend.text = element_text(size = 12),
    axis.text.x = element_blank()
    ) +
  labs(x = "", y = "") 


commute_age_mode_combined

ggsave(filename = "samo_combined_commute_age_mode_bar.png", 
       plot = commute_age_mode_combined, 
       path = file.path(file_path, boulevard, "Outputs"),
       height = 9,
       width = 8.5,
       dpi = 2000)



ancestry_counts <- acs_tracts_boulevard %>% 
  st_drop_geometry() %>% 
  select(starts_with("B04006")) %>%
  select(ends_with(c("016", "048", "001"))) %>% 
  colSums()


```

```{r calculating counts}


#total population
sum(acs_tracts_boulevard$B01001_001)

##percent below poverty
sum(acs_tracts_boulevard$B17001_002) / sum(acs_tracts_boulevard$B17001_001)

##access to computing device
sum(acs_tracts_boulevard$B28001_002) / sum(acs_tracts_boulevard$B28001_001)

##access to vehicle
sum(acs_tracts_boulevard$B25044_003 + acs_tracts_boulevard$B25044_010) / sum(acs_tracts_boulevard$B25044_001)

##number of households with children
sum(acs_tracts_boulevard$B11003_003 + acs_tracts_boulevard$B11003_010 + acs_tracts_boulevard$B11003_016)

##school enrollment
sum(acs_tracts_boulevard$B14007_017 + acs_tracts_boulevard$B14007_018) / sum(acs_tracts_boulevard$B14007_001)

sum(acs_city_la$B14007_017 + acs_city_la$B14007_018) / sum(acs_city_la$B14007_001)

##transportation cost burden
sum(h_and_t_sf$population * h_and_t_sf$t_ami) / sum(h_and_t_sf$population)





buffer_area = boulevard_tracts %>% st_bbox() %>% st_as_sfc()

result1 <- samo_test %>%
        st_transform(4326) %>%
        st_make_valid() 

result2 = result1 %>%
        st_filter(buffer_area %>% st_transform(4326)) %>%
        st_intersection(boulevard_tracts %>% st_transform(4326)) %>%
        janitor::clean_names() %>%
  mutate(zoning_category = case_when(
            zoning %in% c("MUB", "HMU", "MUBL", "OC", "CAC", "CCS", "IC", "MUC", "NC") ~ "Commercial or Industrial",
            zoning %in% c("OS", "PL", "BTV") ~ "Public",
            #zoning %in% c("Parking", "Freeway") ~ "Highways or Parking",
            #zoning %in% c("Agricultural", "Open Space") ~ "Agricultural or Open Space",
            zoning %in% c("R2", "R3", "R4", "RMH") ~ "Multi-family Residential",
            zoning %in% c("R1") ~ "Single-family Residential",
            TRUE ~ zoning) %>%
            factor(
              levels = c(
                "Single-family Residential", "Multi-family Residential", "Public",
                "Agricultural or Open Space", "Commercial or Industrial", 
                "Highways or Parking")))




sum(acs_tracts_boulevard$B14007_017, acs_tracts_boulevard$B14007_018) / sum(acs_tracts_boulevard$B14007_001)


##pop over 16 enrolled in school

sum(acs_tracts_boulevard$B14007_015, acs_tracts_boulevard$B14007_016, acs_tracts_boulevard$B14007_017, acs_tracts_boulevard$B14007_018)/ sum(acs_tracts_boulevard$B23001_001)


```
